name: "Create Tagged Release"

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version number of the release'
        required: true

jobs:
  gh_tagged_release:
    name: Create tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Set app version (Unix)
        run: npm version ${{ github.event.inputs.release_version }} --no-git-tag-version

      - name: Build Project
        run: npm run build

      - name: "Create Github release (full)"
        if: ${{ !contains( github.event.inputs.release_version, '-rc' ) }}
        uses: softprops/action-gh-release@v2
        id: flex_horseshoe_card_release
        with:
          body: "Release version ${{ github.event.inputs.release_version }}."
          tag_name: ${{ github.event.inputs.release_version }}
          target_commitish: "main"
          draft: false
          prerelease: false
          files: flex-horseshoe-card.js
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}